env:
  global:
    - CONAN_BUILD_REQUIRES="ninja/1.9.0"
    - CONAN_CMAKE_GENERATOR=Ninja
    - CONAN_PRINT_RUN_COMMANDS=1
    - CONAN_UPLOAD_ONLY_WHEN_STABLE=0
    - secure: WBWyAJNbuv3PXdLKfXEdiGlJtoTfY/D3HYrk4cHoU0i7mAFkn9pqBS5uGX1XDwytd5x2uevpOm0kJOpoZI8ZgUl277rFaFC5p0blqU078ja3yxWsyMN4rTZLICUUIuQvuoRonAa+2V1+A4FbATThbtDA+PL504vTbPwcNb5rNEDgBw8kq05ORDDZ8pEE1xo4U19ENoq7hT+akZj0NSw1LbFG7M29Dqv7fZSWlKH55U+C6Oun9jme2eySFokSeaklYFjWmbqR72ZXb9Wwzy5WPL0fpMy06GPrWdZOR2h8mbflv7fJ3f7rmbSl9hNpuUx7B8cCc289qbZRPRhxi8EZn5m3AA1Cv/Ut3ZLfwqFUe3UvVaYrCJMhzxegxG8qKksgzNuyM8Hn32qppnGQbcielEfnRiqdK5ulOuVM2aT3ghWx1c/qa0+gVZ6PwX5Nv27j0ZY1K+lXpQmcQ/uwmu0U6dZeVWL9gE2z7NZyv8k+V0WyiFlfof7j5axsizlX1hkU94XyWegaP9O7WkyqMFj+sIwmPV3IwN2GqxiAjFOxV9AtG8PQIb3Es+d0uD0tGdcL4peSDDEH3nKqYDuetV9HtoA1+89q65aBz5oHIQ1KiqUVVe4RY24sRFp5TWe6vSdCuudpsWW815Ubx6aiQeRUGOP/jVS+kTPR7W+NR3KM+yk=

linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc9-armv7hf
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/gcc9-armv8
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
      # libc++ 32 bit is broken in the clang8/clang9 Docker images
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/clang8
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=9 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/clang9
      # - <<: *osx
        # osx_image: xcode10.3
        # env: CONAN_APPLE_CLANG_VERSIONS=10.0
      # - <<: *osx
        # osx_image: xcode11.2
        # env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
