build: false

environment:
  CONAN_PRINT_RUN_COMMANDS: 1
  CONAN_RUN_TESTS: 1
  PYTHON_HOME: "C:\\Python37"
  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Release
        CONAN_ARCHS: x86_64
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 0
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Release
        CONAN_ARCHS: x86
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 0
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Debug
        CONAN_ARCHS: x86_64
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 0
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Debug
        CONAN_ARCHS: x86
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 0

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python .conan/build.py